package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/gastownhall/gascity/internal/fsys"
)

// sessionBdPathShimDir is a directory containing a single executable named
// `bd`. Sessions prepend this directory to PATH so a bare `bd` typed (or
// invoked by a formula step) inside the session resolves to the shim
// instead of the real bd binary.
func sessionBdPathShimDir(cityPath string) string {
	return filepath.Join(cityPath, ".gc", "scripts", "session-bd-path")
}

func sessionBdPathShimScriptPath(cityPath string) string {
	return filepath.Join(sessionBdPathShimDir(cityPath), "bd")
}

// ensureSessionBdPathShim writes the stable per-city bd-shadowing shim.
//
// A managed Dolt server rotates ports (e.g. a restart after 29621 -> 29620,
// gastownhall/gascity#792): `gc bd` re-resolves the canonical endpoint on
// every invocation, but a bare `bd` typed in an already-running session only
// sees the BEADS_DOLT_SERVER_* env baked into that session at creation time,
// so it keeps targeting the dead port. Following bd's own recovery hint in
// that state (`bd dolt start`) boots a second, divergent, empty Dolt server
// instead of reaching the live one.
//
// The shim closes that gap by making `bd` resolve to `gc bd "$@"` for every
// session, so a bare bd call gets the same call-time canonical resolution
// (and the same refusal to suggest a divergent `bd dolt start`, see
// bdDoltStartConflictUserMessage in cmd_bd.go) that `gc bd` already has. It
// execs the currently running gc binary, so no session recycling is needed
// when only the Dolt port changes — just when the gc binary itself is
// upgraded, which is when this shim is next regenerated.
//
// Cities on non-bd providers skip it, matching ensureGcBeadsBdShim.
func ensureSessionBdPathShim(cityPath string) error {
	if !cityUsesBdStoreContract(cityPath) {
		return nil
	}
	gcExe, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolving gc binary path for session bd shim: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(gcExe); err == nil && resolved != "" {
		gcExe = resolved
	}
	shim := fmt.Sprintf(`#!/bin/sh
# Generated by gc — do not edit. Shadows the bare "bd" binary for this
# session so a managed Dolt endpoint rotation cannot strand it on a stale
# port: gc bd re-resolves the canonical endpoint on every call instead of
# trusting env baked in at session start. See gastownhall/gascity#792.
exec %q bd "$@"
`, gcExe)
	path := sessionBdPathShimScriptPath(cityPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return fsys.WriteFileIfContentOrModeChangedAtomic(fsys.OSFS{}, path, []byte(shim), 0o755)
}
